import { type NextRequest, NextResponse } from "next/server"

const paragraphTopicsData = {
  english: [
    {
      id: 1,
      title: "Personal Stories",
      description: "Translate personal narratives and life experiences",
      icon: "📖",
      level: "Beginner",
      paragraphsCount: 8,
      difficulty: "Easy",
      color: "blue",
      estimatedTime: "45 minutes",
      topics: ["Daily routine", "Childhood memories", "Personal experiences"],
      averageLength: "4-6 sentences",
    },
    {
      id: 2,
      title: "Travel Adventures",
      description: "Stories about traveling and exploring new places",
      icon: "🌍",
      level: "Intermediate",
      paragraphsCount: 10,
      difficulty: "Medium",
      color: "emerald",
      estimatedTime: "60 minutes",
      topics: ["Travel experiences", "Cultural differences", "Adventure stories"],
      averageLength: "6-8 sentences",
    },
    {
      id: 3,
      title: "Food & Culture",
      description: "Paragraphs about food traditions and cultural practices",
      icon: "🍜",
      level: "Intermediate",
      paragraphsCount: 12,
      difficulty: "Medium",
      color: "orange",
      estimatedTime: "70 minutes",
      topics: ["Traditional dishes", "Cooking methods", "Food culture"],
      averageLength: "7-9 sentences",
    },
    {
      id: 4,
      title: "Technology Impact",
      description: "Complex texts about technology and its effects on society",
      icon: "🤖",
      level: "Advanced",
      paragraphsCount: 15,
      difficulty: "Hard",
      color: "purple",
      estimatedTime: "90 minutes",
      topics: ["Digital transformation", "AI impact", "Future technology"],
      averageLength: "8-12 sentences",
    },
    {
      id: 5,
      title: "Environmental Issues",
      description: "Paragraphs about climate change and environmental topics",
      icon: "🌱",
      level: "Advanced",
      paragraphsCount: 14,
      difficulty: "Hard",
      color: "green",
      estimatedTime: "85 minutes",
      topics: ["Climate change", "Conservation", "Sustainability"],
      averageLength: "9-12 sentences",
    },
    {
      id: 6,
      title: "Business & Economics",
      description: "Professional texts about business and economic topics",
      icon: "📊",
      level: "Advanced",
      paragraphsCount: 16,
      difficulty: "Hard",
      color: "slate",
      estimatedTime: "100 minutes",
      topics: ["Market analysis", "Business strategy", "Economic trends"],
      averageLength: "10-15 sentences",
    },
    {
      id: 7,
      title: "Health & Wellness",
      description: "Articles about health, fitness, and medical topics",
      icon: "💪",
      level: "Intermediate",
      paragraphsCount: 11,
      difficulty: "Medium",
      color: "red",
      estimatedTime: "65 minutes",
      topics: ["Exercise benefits", "Nutrition", "Mental health"],
      averageLength: "6-9 sentences",
    },
    {
      id: 8,
      title: "Science & Discovery",
      description: "Scientific articles and research findings",
      icon: "🔬",
      level: "Advanced",
      paragraphsCount: 13,
      difficulty: "Hard",
      color: "cyan",
      estimatedTime: "80 minutes",
      topics: ["Research findings", "Scientific methods", "Discoveries"],
      averageLength: "8-11 sentences",
    },
  ],
  japanese: [
    {
      id: 1,
      title: "個人的な話 (Personal Stories)",
      description: "Translate personal narratives and life experiences",
      icon: "📖",
      level: "Beginner",
      paragraphsCount: 8,
      difficulty: "Easy",
      color: "blue",
      estimatedTime: "45 minutes",
      topics: ["日常生活", "子供の頃の思い出", "個人的な経験"],
      averageLength: "4-6 sentences",
    },
    {
      id: 2,
      title: "旅行の冒険 (Travel Adventures)",
      description: "Stories about traveling and exploring new places",
      icon: "🌍",
      level: "Intermediate",
      paragraphsCount: 10,
      difficulty: "Medium",
      color: "emerald",
      estimatedTime: "60 minutes",
      topics: ["旅行体験", "文化の違い", "冒険の話"],
      averageLength: "6-8 sentences",
    },
    {
      id: 3,
      title: "食べ物と文化 (Food & Culture)",
      description: "Paragraphs about food traditions and cultural practices",
      icon: "🍜",
      level: "Intermediate",
      paragraphsCount: 12,
      difficulty: "Medium",
      color: "orange",
      estimatedTime: "70 minutes",
      topics: ["伝統料理", "料理方法", "食文化"],
      averageLength: "7-9 sentences",
    },
    {
      id: 4,
      title: "技術の影響 (Technology Impact)",
      description: "Complex texts about technology and society",
      icon: "🤖",
      level: "Advanced",
      paragraphsCount: 15,
      difficulty: "Hard",
      color: "purple",
      estimatedTime: "90 minutes",
      topics: ["デジタル変革", "AI の影響", "未来の技術"],
      averageLength: "8-12 sentences",
    },
  ],
}

export async function GET(request: NextRequest, { params }: { params: { language: string } }) {
  try {
    const language = params.language as keyof typeof paragraphTopicsData

    if (!paragraphTopicsData[language]) {
      return NextResponse.json({ success: false, message: "Language not supported" }, { status: 404 })
    }

    return NextResponse.json({
      success: true,
      data: paragraphTopicsData[language],
    })
  } catch (error) {
    return NextResponse.json({ success: false, message: "Server error" }, { status: 500 })
  }
}
